export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",

    PROFILE_BLOG_DELETE: "PROFILE_BLOG_DELETE",
  },
  blog: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
    DATA_CREATED: "BLOG_DATA_CREATED",
    POST_DELETED: "BLOG_DATA_DELETED",

    BLOGS_DATA: "BLOGS_DATA",
    BLOGS_DATA_EDIT: "BLOGS_DATA_EDIT",
    DATA_LIKE: "BLOG_DATA_LIKE",
    DATA_FAVOURITE: "BLOG_DATA_FAVOURITE",
    DATA_COMMENT_DELETE: "BLOG_DATA_COMMENT_DELETE",
    DATA_CLEAR: "DATA_CLEAR",
  },
};
