const student = {
  classOne: [
    {
      id: 1,
      class: "One",
      name: "rony Das",
      scores: "A+",
      percentage: 98,
      image: "https://xsgames.co/randomusers/assets/avatars/male/1.jpg",
    },
    {
      id: 2,
      class: "One",
      name: "Smith",
      scores: "A",
      percentage: 99,
      image: "https://xsgames.co/randomusers/assets/avatars/male/2.jpg",
    },
    {
      id: 3,
      class: "One",
      name: "Emily Johnson",
      scores: "B+",
      percentage: 89,
      image: "https://xsgames.co/randomusers/assets/avatars/male/3.jpg",
    },
    {
      id: 4,
      class: "One",
      name: "Alex Rodriguez",
      scores: "A-",
      percentage: 92,
      image: "https://xsgames.co/randomusers/assets/avatars/male/4.jpg",
    },
    {
      id: 5,
      class: "One",
      name: "Sophie White",
      scores: "B",
      percentage: 78,
      image: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
    },
    {
      id: 6,
      class: "One",
      name: "Chris Evans",
      scores: "A",
      percentage: 95,
      image: "https://xsgames.co/randomusers/assets/avatars/male/6.jpg",
    },
    {
      id: 7,
      class: "One",
      name: "Olivia Parker",
      scores: "B-",
      percentage: 81,
      image: "https://xsgames.co/randomusers/assets/avatars/male/7.jpg",
    },
    {
      id: 8,
      class: "One",
      name: "Daniel Smith",
      scores: "A+",
      percentage: 97,
      image: "https://xsgames.co/randomusers/assets/avatars/male/8.jpg",
    },
    {
      id: 9,
      class: "One",
      name: "Ava Davis",
      scores: "B",
      percentage: 87,
      image: "https://xsgames.co/randomusers/assets/avatars/male/9.jpg",
    },
    {
      id: 10,
      class: "One",
      name: "Ethan Brown",
      scores: "A-",
      percentage: 91,
      image: "https://xsgames.co/randomusers/assets/avatars/male/10.jpg",
    },
  ],
  classTwo: [
    {
      id: 1,
      class: "Two",
      name: "Eva Thompson",
      scores: "A+",
      percentage: 98,
      image: "https://xsgames.co/randomusers/assets/avatars/male/11.jpg",
    },
    {
      id: 2,
      class: "Two",
      name: "Lucas Baker",
      scores: "A",
      percentage: 99,
      image: "https://xsgames.co/randomusers/assets/avatars/male/12.jpg",
    },
    {
      id: 3,
      class: "Two",
      name: "Avery Parker",
      scores: "A-",
      percentage: 92,
      image: "https://xsgames.co/randomusers/assets/avatars/male/13.jpg",
    },
    {
      id: 4,
      class: "Two",
      name: "Logan Mitchell",
      scores: "A+",
      percentage: 96,
      image: "https://xsgames.co/randomusers/assets/avatars/male/14.jpg",
    },
    {
      id: 5,
      class: "Two",
      name: "Sophie Anderson",
      scores: "B+",
      percentage: 88,
      image: "https://xsgames.co/randomusers/assets/avatars/male/15.jpg",
    },
    {
      id: 6,
      class: "Two",
      name: "Mason Turner",
      scores: "A",
      percentage: 95,
      image: "https://xsgames.co/randomusers/assets/avatars/male/16.jpg",
    },
    {
      id: 7,
      class: "Two",
      name: "Zoe Harrison",
      scores: "B-",
      percentage: 81,
      image: "https://xsgames.co/randomusers/assets/avatars/male/17.jpg",
    },
    {
      id: 8,
      class: "Two",
      name: "Leo Wright",
      scores: "A-",
      percentage: 91,
      image: "https://xsgames.co/randomusers/assets/avatars/male/18.jpg",
    },
    {
      id: 9,
      class: "Two",
      name: "Aria Reed",
      scores: "B",
      percentage: 87,
      image: "https://xsgames.co/randomusers/assets/avatars/male/19.jpg",
    },
    {
      id: 10,
      class: "Two",
      name: "Elijah Foster",
      scores: "A",
      percentage: 94,
      image: "https://xsgames.co/randomusers/assets/avatars/male/20.jpg",
    },
  ],
  classThree: [
    {
      id: 1,
      class: "Three",
      name: "Natalie Foster",
      scores: "A-",
      percentage: 93,
      image: "https://xsgames.co/randomusers/assets/avatars/male/21.jpg",
    },
    {
      id: 2,
      class: "Three",
      name: "Ethan Carter",
      scores: "A+",
      percentage: 97,
      image: "https://xsgames.co/randomusers/assets/avatars/male/22.jpg",
    },
    {
      id: 3,
      class: "Three",
      name: "Grace Mitchell",
      scores: "B+",
      percentage: 89,
      image: "https://xsgames.co/randomusers/assets/avatars/male/23.jpg",
    },
    {
      id: 4,
      class: "Three",
      name: "Caleb Walker",
      scores: "A",
      percentage: 94,
      image: "https://xsgames.co/randomusers/assets/avatars/male/24.jpg",
    },
    {
      id: 5,
      class: "Three",
      name: "Zoe Harris",
      scores: "B",
      percentage: 86,
      image: "https://xsgames.co/randomusers/assets/avatars/female/25.jpg",
    },
    {
      id: 6,
      class: "Three",
      name: "Oliver Turner",
      scores: "A-",
      percentage: 90,
      image: "https://xsgames.co/randomusers/assets/avatars/male/26.jpg",
    },
    {
      id: 7,
      class: "Three",
      name: "Sophia Davis",
      scores: "B-",
      percentage: 82,
      image: "https://xsgames.co/randomusers/assets/avatars/female/27.jpg",
    },
    {
      id: 8,
      class: "Three",
      name: "Mason White",
      scores: "A",
      percentage: 96,
      image: "https://xsgames.co/randomusers/assets/avatars/male/28.jpg",
    },
    {
      id: 9,
      class: "Three",
      name: "Ava Thompson",
      scores: "B+",
      percentage: 88,
      image: "https://xsgames.co/randomusers/assets/avatars/female/29.jpg",
    },
    {
      id: 10,
      class: "Three",
      name: "Liam Harrison",
      scores: "A+",
      percentage: 98,
      image: "https://xsgames.co/randomusers/assets/avatars/male/30.jpg",
    },
  ],
};
export default student;
