const bookData = [
  {
    id: 1,
    title: "Slow Horses ",
    author: "Mick Herron",
    thumbnail:
      "https://m.media-amazon.com/images/I/51Ga5GuElyL._SX331_BO1,204,203,200_.jpg",
    price: 120,
    rating: 4,
    isFavorite: false,
    releaseDate: 2002,
  },
  {
    id: 2,
    title: "The Last Thing He Told Me: A Novel",
    author: "Laura Dave",
    thumbnail:
      "https://m.media-amazon.com/images/P/1501171348.01._SCLZZZZZZZ_SX500_.jpg",
    price: 13.99,
    rating: 3,
    isFavorite: false,
    releaseDate: 2008,
  },
  {
    id: 3,
    title: "Eloquent JavaScript, 3rd Edition",
    author: "Marijn Haverbeke",
    thumbnail:
      "https://m.media-amazon.com/images/I/51InjRPaF7L._SX377_BO1,204,203,200_.jpg",
    price: 23.99,
    rating: 4,
    isFavorite: false,
    releaseDate: 2012,
  },
  {
    id: 4,
    title: "Zpractical MongoDB",
    author: "Emily Sterling",
    price: 32.04,
    thumbnail: "https://itbook.store/img/books/9781484206485.png",
    rating: 5,
    isFavorite: true,
    releaseDate: 2015,
  },
  {
    id: 5,
    title: "A Definitive Guide to MongoDB, 3rd Edition",
    author: "Samuel Hawthorne",
    price: 47.11,
    thumbnail: "https://itbook.store/img/books/9781484211830.png",
    rating: 2,
    isFavorite: false,
    releaseDate: 2005,
  },
  {
    id: 6,
    title: "MongoDB in Action, 2nd Edition",
    author: "Isabella Montague",
    price: 32.1,
    thumbnail: "https://itbook.store/img/books/9781617291609.png",
    rating: 4,
    isFavorite: false,
    releaseDate: 2009,
  },
  {
    id: 7,
    title: "Designing Across Senses",
    author: "Oliver Quinn",
    price: 27.59,
    thumbnail: "https://itbook.store/img/books/9781491954249.png",
    rating: 2,
    isFavorite: false,
    releaseDate: 2007,
  },
  {
    id: 8,
    title: "Web Scraping with Python, 2nd Edition",
    author: "Victoria Sinclair",
    price: 33.99,
    thumbnail: "https://itbook.store/img/books/9781491985571.png",
    rating: 5,
    isFavorite: false,
    releaseDate: 2020,
  },
  {
    id: 9,
    title: "Programming iOS 11",
    author: "Marcus Blackwood",
    price: 59.17,
    thumbnail: "https://itbook.store/img/books/9781491999226.png",
    rating: 1,
    isFavorite: false,
    releaseDate: 2022,
  },
  {
    id: 10,
    title: "Norwegian Wood",
    author: "Penelope Harper",
    price: 70,
    thumbnail:
      "http://t1.gstatic.com/images?q=tbn:ANd9GcQvJJDi2mzwg9v_PlmKYL31gXIz0kvAObJak7DVFPcD_mJTIyec",
    rating: 3,
    isFavorite: false,
    releaseDate: 2020,
  },
];

export default bookData;
